name: Convert Markdown to PDF

on:
  push:
    paths:
      - '**.md'
  workflow_dispatch:
    inputs:
      markdown_file:
        description: 'Specific markdown file to convert'
        required: false
        type: string

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Convert Markdown to PDF
        uses: your-username/markdown-to-pdf-action@v1
        with:
          markdown_dir: './docs'
          markdown_file: ${{ github.event.inputs.markdown_file }}
          output_dir: './pdf-output'
          table_of_contents: 'true'
          highlight_style: 'github'
          pdf_options: '{"format": "A4", "margin": {"top": "50px", "right": "50px", "bottom": "50px", "left": "50px"}}'
      
      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf-files
          path: './pdf-output/*.pdf'